print("====================================")
print("Benvenuto")
print("Seleziona l'opearazione da eseguire: ")
print("1 = Addizione")
print("2 = Sottrazione")
print("3 = Moltiplicazione")
print("4 = Divisione")
print("5 = Modulo")
print("====================================")
print(" ")
scelta = input("Inserire una scelta valida: ")
if scelta not in ['1','2','3','4','5']:
        print ("Scelta non valida")
        wait = input("Premi un tasto per uscire.")
        print("closing...")
if scelta == '1':
    a = input("Inserisci Primo Valore: ")
    b = input("Inserisci Secondo Valore: ")
    x=int(a)+int(b)
    print ("la somma è: ",x)
    wait = input("Premi un tasto per uscire.")
    print("closing...")
elif scelta == '2':
    a = input("Inserisci Primo Valore: ")
    b = input("Inserisci Secondo Valore: ")
    x=int(a)-int(b)
    print ("la differenza è: ",x)
    wait = input("Premi un tasto per uscire.")
    print("closing...")
elif scelta == '3':
    a = input("Inserisci Primo Valore: ")
    b = input("Inserisci Secondo Valore: ")
    x=int(a)*int(b)
    print ("il prodotto è: ",x)
    wait = input("Premi un tasto per uscire.")
    print("closing...")
elif scelta == '4':
    a = input("Inserisci Primo Valore: ")
    b = input("Inserisci Secondo Valore: ")
    x=int(a)/int(b)
    print ("il quoziente è: ",x)
    wait = input("Premi un tasto per uscire.")
    print("closing...")
elif scelta == '5':
    a = input("Inserisci Primo Valore: ")
    b = input("Inserisci Secondo Valore: ")
    x=int(a)%int(b)
    print ("il modulo è: ",x)
    wait = input("Premi un tasto per uscire.")
    print("closing...")